spring:
  application:
    name: "spellbook"
  h2:
    console:
      enabled: false
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:spellbookapp
    username: sb
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
